// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class Article
{
    public int ContentId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int Creator { get; set; }

    public DateTime Date { get; set; }

    public string Image { get; set; }

    public string Tag { get; set; }

    public bool Status { get; set; }

    public virtual Registeruser CreatorNavigation { get; set; }
}