// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class Diamond
{
    public int DiamondId { get; set; }

    public string Shape { get; set; }

    public string Color { get; set; }

    public string Clarity { get; set; }

    public decimal? Carat { get; set; }

    public string Cut { get; set; }

    public string CertificateScan { get; set; }

    public int AmountAvailable { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<Orderdetail> Orderdetails { get; set; } = new List<Orderdetail>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}