// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class Purchaseorder
{
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public DateTime Date { get; set; }

    public string PaymentMethod { get; set; }

    public string ShippingAddress { get; set; }

    public decimal TotalPrice { get; set; }

    public string OrderStatus { get; set; }

    public int? PromotionId { get; set; }

    public bool PayWithPoint { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<Orderdetail> Orderdetails { get; set; } = new List<Orderdetail>();

    public virtual Promotion Promotion { get; set; }

    public virtual Registeruser User { get; set; }
}