// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class Shell
{
    public int ShellId { get; set; }

    public string Name { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<Shellinventory> Shellinventories { get; set; } = new List<Shellinventory>();
}