// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class Shellinventory
{
    public int ShellInventoryId { get; set; }

    public int ShellId { get; set; }

    public decimal Size { get; set; }

    public decimal Price { get; set; }

    public int AmountAvailable { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<Orderdetail> Orderdetails { get; set; } = new List<Orderdetail>();

    public virtual Shell Shell { get; set; }
}