// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class Size
{
    public int CategoryId { get; set; }

    public decimal? MinSize { get; set; }

    public decimal? MaxSize { get; set; }

    public decimal? Step { get; set; }

    public virtual Category Category { get; set; }
}