// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class Diamond
{
    public int DiamondId { get; set; }

    public int? MainDiamondAtrributeId { get; set; }

    public string CertificateScan { get; set; }

    public int? OrderDetailId { get; set; }

    public decimal Price { get; set; }

    public bool Status { get; set; }

    public virtual Diamondattribute MainDiamondAtrribute { get; set; }

    public virtual Orderdetail OrderDetail { get; set; }
}