// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class Diamond
{
    public int DiamondId { get; set; }

    public string Shape { get; set; }

    public string Color { get; set; }

    public string Clarity { get; set; }

    public decimal? Carat { get; set; }

    public string Cut { get; set; }

    public string CertificateScan { get; set; }

    public decimal Price { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<Product> ProductMainDiamonds { get; set; } = new List<Product>();

    public virtual ICollection<Product> ProductSubDiamonds { get; set; } = new List<Product>();
}