// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class Notification
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public string Message { get; set; }

    public bool IsDelivered { get; set; }

    public DateTime CreatedAt { get; set; }

    public string ConnectionId { get; set; }

    public bool MarkRead { get; set; }
}