// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class ProductDiamond
{
    public int ProductId { get; set; }

    public int DiamondId { get; set; }

    public bool Status { get; set; }

    public virtual Diamond Diamond { get; set; }

    public virtual Product Product { get; set; }
}