// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductCode { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public string Description { get; set; }

    public decimal? LaborCost { get; set; }

    public string ImageLinkList { get; set; }

    public bool Status { get; set; }

    public int? MainDiamondAmount { get; set; }

    public int? SubDiamondAmount { get; set; }

    public int? CollectionId { get; set; }

    public int? CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual Collection Collection { get; set; }

    public virtual ICollection<Diamond> Diamonds { get; set; } = new List<Diamond>();

    public virtual ICollection<Orderdetail> Orderdetails { get; set; } = new List<Orderdetail>();

    public virtual ICollection<Shell> Shells { get; set; } = new List<Shell>();
}