// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DIAN_.Models;

public partial class Purchaseorder
{
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public DateTime Date { get; set; }

    public string PaymentMethod { get; set; }

    public string Name { get; set; }

    public string PhoneNumber { get; set; }

    public string ShippingAddress { get; set; }

    public decimal TotalPrice { get; set; }

    public string OrderStatus { get; set; }

    public int? PromotionId { get; set; }

    public bool? PayWithPoint { get; set; }

    public string Note { get; set; }

    public int? SaleStaff { get; set; }

    public int? DeliveryStaff { get; set; }

    public virtual Employee DeliveryStaffNavigation { get; set; }

    public virtual ICollection<Orderdetail> Orderdetails { get; set; } = new List<Orderdetail>();

    public virtual Promotion Promotion { get; set; }

    public virtual Employee SaleStaffNavigation { get; set; }

    public virtual Customer User { get; set; }
}